services:
  - type: web
    name: backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
  
  - type: web
    name: frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
